const Appapis = {
    // Basurl: "https://specsauradataplazma.vercel.app/api",
    Basurl: "https://api.specsaura.com/api",
    signIn: "/request",
    signOut: "/signOut",
    verifyOtp: "/verify",
    contact: "/contact",
    prescription: "/presc",
    fileUpload: "/upload",
    ctegory: "/category",
    wallpaper: "/wallpaper",
    product: "/products/all",
    productSearch: "/products/search",
    cart: "/cart",
    productDetail: (id) => `/product/${id}`,
    createPayment: "/createPaymentOrder",
    verify: "/varifyPayment",
    cartItems: (id) => `/cart/all/${id}`,
    deleteCart: (id) => `/cart/${id}`,
    createOrder: "/order",
    Getuser: "/user/info",
    getOrder: (id) => `/orders/user/${id}`,
    updateUser: `/user/update/`,
    deleteFullCart: "/cart",
    getCartMany: "/cart",
    getSingleCart: (id) => `/cart/${id}`,
    updateCartFlag: (id) => `/cart/flag/${id}`,
    updateCart: (id) => `/cart/${id}`,
    lenseType: (name) => `/lenseType/${name}`,
    getBlog: `/blog`,
    lensDetail: (name) => `/lens/${name}`,
    sendorder: "/order/email",
    getRate: "/gstrate",
    accessoriesAll: "/accessories/all",
    accessoriesByCategory: (id) => `/accessories/category/${id}`,
    orderAll: "/order/all"
}

export default Appapis